### ISSUE TITLE
Upgrade internals to latest compiler version

### ISSUE THREAD

**Issue by KaiserKarel** [KaiserKarel/substrace#3]
Substrace uses relatively old compiler internals (rustc_ast etc). We should upgrade ASAP to ensure we don't drift to much from `head` or latest `nightly`. This'll require changing the `clippy_utils` library, updating rust-toolchain.toml and fixing compilation issues.

**Comment by TheCodingWombat** [comment]
Agreed with @KaiserKarel that we will aim for "nightly-2022-11-21".
